site_name: SootUp
site_url: https://soot-oss.github.io/SootUp/
repo_url: https://github.com/soot-oss/SootUp/
edit_uri: edit/develop/docs/

nav:
    - Home: index.md
    - Announcements: announce.md
    - Design Decisions: whatsnew.md

    - Basics:
      - Installation: installation.md
#      - Configure your Input: analysisinputlocations.md
      - Getting started: getting-started.md
      - Jimple: jimple.md

    - Advanced Topics:
      - BodyInterceptors: bodyinterceptors.md
      - Call Graph Construction: call-graph-construction.md
      - SootUp Utilities: advanced-topics.md

    - How to..:
      - Write an Analysis: write_analyses.md
    #  - Modify a StmtGraph: mutable_stmtgraph.md
    #  - Modify a View: mutable_view.md
    #  - Implement a BodyInterceptor: body_interceptor.md
    #  - Implement an AnalysisTool: write_analysis_tool.md

    - More information:
      - Javadoc: /SootUp/apidocs
      - Troubleshooting & FAQ: faq.md
      # - Based on SootUp: tools.md

theme:
  palette:
    primary: white
  name: material
  logo: ./SootUpLogo.svg
  favicon: ./icon.svg
  features:
    - navigation.sections

plugins:
  - tooltips
  - search
  - include:
      src_path: 'sootup.examples/src/test/java/sootup/examples'

extra_css:
  - css/hint.min.css

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      use_pygments: true
      extend_pygments_lang:
        - name: jimple
          lang: lspserver
          options:
            filetype: jimple
            # the path of the jimplelsp.jar needs to be the same as in the gh-pages.yml workflow
            lspcommand: "java -jar ./jimplelsp.jar"

  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - pymdownx.tabbed:
      alternate_style: true

extra:
  version:
    provider: mike